services:
  tts:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: tts-service

    ports:
      - "8000:8000"

    volumes:
      - ./models:/app/models
      - ./output:/app/output

    restart: unless-stopped

